import type { Metadata } from "next";
import localFont from "next/font/local";
import StoryblokProvider from "./components/StoryblokProvider";
import "./globals.css";
import styles from "./layout.module.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <div className={styles.page}>

            <nav className={styles.nav}>
              <a href="/">Home</a>
              <a href="/about">About</a>
            </nav>
            {children}
            <footer className={styles.footer}>
              <p>Powered by Storyblok</p>
            </footer>
          </div>
        </body>
      </html>
    </StoryblokProvider>
  );
}
